# Generated by Django 5.2.5 on 2025-08-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_alter_genre_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
    ]
