# Generated by Django 5.2.5 on 2025-09-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('FRA', 'França'), ('ITA', 'Itália'), ('GBR', 'Reino Unido'), ('DEU', 'Alemanha'), ('IND', 'Índia'), ('CHN', 'China'), ('JPN', 'Japão'), ('KOR', 'Coreia do Sul'), ('BRA', 'Brasil'), ('ESP', 'Espanha'), ('MEX', 'México'), ('RUS', 'Rússia'), ('CAN', 'Canadá'), ('SWE', 'Suécia'), ('AUS', 'Austrália'), ('ARG', 'Argentina'), ('IRN', 'Irã'), ('HKG', 'Hong Kong'), ('EGY', 'Egito')], max_length=100, null=True, verbose_name='Nacionalidade')),
            ],
        ),
    ]
